### ISSUE TITLE
demo_doublegauss: Exception: glass name N-SK16 not found (w/ solution)

### ISSUE THREAD

**Issue by calocedrus** [mess42/pyrate#132]
When running the doublegauss demo (demo_doublegauss.py), I ran into an exception: 
`Exception: glass name N-SK16 not found`

My environment: Linux ubuntu 18.04, installed pyrate by cloning the repository, installation in a virtualenvironment, python 3.6, all dependencies properly installed.

I've been able to solve the problem by:

- cloning the refractiveindex.info-database repo (when cloning pyrate, the `pyrateoptics/refractiveindex.info-database` directory was empty)
- changing `db_path` in `demo_doublegauss.py` from `refractiveindex.info-database/database` to `pyrateoptics/refractiveindex.info-database/database`

I'm not sure if I did anything wrong in my installation but I wanted to report this in case others encounter this issue.

**Comment by joha2** [comment]
@calocedrus thanks for the issue report! Your install process is perfectly fine for Pyrate. Further, we use `refractiveindex.info` as our material database. (If you don't know the material parameters, but the name of the material, it is very useful.) We implemented it as a submodule, so `git submodule init` and `git submodule update` should fill up the directory. We are not sure, how to reference to `refractiveindex.info` effectively, since it is a sub directory in Pyrate and use relative paths in the demos. We consider this solution as not optimal, therefore we are always interested in ideas of doing it better. Perhaps one can use a config file and initialize the db with a search path: The counter indications for that are: First you have to initialize the config file in every demo file, and second you pollute the global namespace with search path directories. If there is a better idea, just shoot :-)

Best wishes
Johannes

**Comment by joha2** [comment]
@calocedrus will be fixed by #162 where I wrote appropriate install instructions together with an easy to use ConfigFile interface. After acceptance of the PR I will change the demo files accordingly.
