### ISSUE TITLE
Using Pyrate with existing CAD model

### ISSUE THREAD

**Issue by dror84** [mess42/pyrate#134]
Hi,
Is it possible to use Pyrate to trace rays in an environment created in Freecad itself? (instead of setting up the optical configuration by hand). 
I would like to assign optical properties to a given object, define source and detector locations and then trace rays and analyse the results.

Thanks

**Comment by joha2** [comment]
Hi @dror84 Thanks for your suggestion. This is definitely a planned feature, in particular for a non-sequential raytracing, but it is far from being implemented. At the moment we are still in a refactoring which turns out to be quite difficult. Then we will reactivate the FreeCAD interface and afterwards, we will try to implement new features (although I am not sure about the best way to do it.).

Best wishes
Johannes
