### ISSUE TITLE
Help on using pyrate module

### ISSUE THREAD

**Issue by ppfromero-lab** [mess42/pyrate#136]
Hello,

I have install pyrate module on FreeCAD and open few examples. Very good job for developpers.
I want to know additionally if this module work for 3D simulations.
I want to import several lenses and mechanical mounting parts in step format and try to make 3D raytracing.
This is possible with pyrate?
It's possible to define laser sources? beam profiles etc???

I have the following error when try to add surfaces

`list index out of rangeRunning the Python command 'CreateSurfacesCommand' failed:

Traceback (most recent call last):

File "/home/jose/.FreeCAD/Mod/pyrate/freecad/PyrateWorkbench/Commands_Surface.py", line 59, in Activated

panel = SurfacesTaskPanelAdd(doc)

File "/home/jose/.FreeCAD/Mod/pyrate/freecad/PyrateWorkbench/TaskPanel_Surfaces_Add.py", line 52, in __init__

self.updateComboLCfromComboOS(self.form.comboBoxOS, self.form.comboBoxLC)

File "/home/jose/.FreeCAD/Mod/pyrate/freecad/PyrateWorkbench/TaskPanel_Surfaces_Add.py", line 63, in updateComboLCfromComboOS

combolc.addItems([lc.Label for lc in oss[0].Proxy.returnObjectsFromCoordinatesGroup()])

list index out of range`

Thanks for your help

**Comment by joha2** [comment]
Hey @ppfromero-lab thanks for reporting of this issue. The FreeCAD workbench is broken since our last large refactoring. Currently, we are rewriting the constructors in a more optimal manner to allow serialization, but it's a tedious task. Therefore, the broken FreeCAD interface is postponed until the core code is running again and supports serialization. This is a necessary ingredient to maintain the status of the optical system throughout the development process in FreeCAD.

The 3D raytracing works already throughout the core code, but in FreeCAD it is not operational. The application of beam profiles or lenses as 3D models is definitely on our TODO list, but the introduction of new features is postponed until the actual refactoring is completed.

Best wishes
Johannes

**Comment by ppfromero-lab** [comment]
Many thanks for your reply,
I think that your development will be very useful and can be an Opensource
solution to Zemax, Lightools and TracePro.
Please let us know news about your developments.

Regards

Jose
