### ISSUE TITLE
Where do i find the order of the optimizable vector

### ISSUE THREAD

**Issue by LeErnst** [mess42/pyrate#137]
Hello,

we want to work with pyrate and we do not know how to determine the order of the optimizable vector, so let say we have given:
-surf1: decx, decz
-surf2: curvature, dez

How do i determine the order in the optimizable vector x?
like: x=(surf1 decx, surf1 decz, surf2 curvature, surf2 dez) 
We need to know for our own optimize algorithms to set the boundary conditions.

**Comment by joha2** [comment]
Hey @LeErnst thanks for using pyrate! Unfortunately, there is now way to reconstruct the order of the elements, once they are converted into a numpy vector. Further, you cannot rely on that they are always in the same order.  The idea is, that the optimizer is very dumb and only knows that there is some merit function which has to be optimized in terms of some independent variables. Therefore, the optimizer could be very generic (i.e. ParticleSwarm, SimulatedAnnealing, NelderMead, etc...) without being constrained by the underlying problem. Usually it is expected, that for the final optimization of some optical system, there is more than one optimizer in a subsequent manner necessary.

For fixed boundary conditions there is an interface in `FloatOptimizableVariable` where you can set an interval via `setInterval`. This maps an infinite parameter space onto a finite interval via a specific transform and also provides the inverse transform in a transparent manner. If the transformation is more complicated, maybe it would be good idea to define a pickup variable (there you can provide an arbitrary function), which is optimized afterwards on a finite or infinite interval. Soft boundary conditions are to be implemented into the merit function. Notice, within the merit function you can also access the variables by accessing the single system variable and call `evaluate` on the specific optimizable variables. Notice further, the code is not tested very thoroughly. Expect bugs. I will provide some example code later, if you are interested.

Best wishes
Johannes

**Comment by LeErnst** [comment]
Hey @joha2 thanks for your fast response. So what we are exactly doing is, we set the intervals for the VariableState variables with setInterval, then we have changed the transformation to the identity mapping, because the transformation is not a good idea anyway (the boundary values were never be reached, the condition of your problem could be really bad and so on). For Optimization we have then implemented our own scipy backend to call the minimize-scipy-function in order to pass our costum-optimization methods. The function which is optimized then is the penalty-lagrange function: G(x)=MeritFunctionWrapper(x)+lambda^T * h(x) + tau*||h(x)||^2, whereby h(x) is a vector valued function h:|R^N -> |R^2N, N is the number of variables, the entries of h(x) are the box-constraints, for instance h_1(x) = max{0,x_1 - b_1}, h_2(x) =max{0, -x_1+a_1}, (x_1 is the first optimizable variable, so lets say it is surf1_decz) x_1 should be in the interval [a_1,b_1] , and for the function h(x) we need to know which entry of x belongs to which interval/variable (in this case x_1 is surf1_decz). So when the opticalsystem, the optimize backend and the opticalsystem analysis object are created there is no way to query the order? But in which way is the initial value x0 set? Somewhere you need to iterate over the Stateobjects and query which variable is in Variablestate in order to create x0, right? Or is it set in a random fashion? That would be a problem for us. 

Thanks,
Lewin

**Comment by joha2** [comment]
Hey @LeErnst,

Thanks for your fast response, too. This is complicated stuff. Let me quickly repeat your points, such that we are sure, I understand correctly:

* The box transformation, we suggest in our code is of no use, since the end points of the inveral are never reached.
* Therefore, you have implemented your own merit function by using our wrapper plus some penalty terms where you want to implement the box constraints in a more or less soft manner.
* For designing the function h(x) you need to know the order of the elements in x such that the box parameters can be tuned accordingly.

Is that correct? Let me think about this. We are collecting the variables via the `OptimizableVariableCollector` in `core/iterators.py`. This is due to the recursive manner we construct the vector `x` from the `ClassWithOptimizableVariable`. I think the collection is more or less predictable and reproducible, but I am not aware how to implement this into your modified merit function approach.

For the other questions at the end of your response:
* This variable `x0` is set via the same `OptimizableVariableCollector` interface. So maybe this would be a good starting point for obtaining the mapping.
* `x0` is set in a random fashing for the raw optimizers `ParticleSwarm` and `SimulatedAnnealing` only. But that's due to the optimizers do not know about the particular order of the elements. But maybe we can add an interface to obtain type or name of a variable from the optimizer itself. At the end of the day this leads to more specialized optimizers, which was not our intension at the beginning, but if this is necessary at the end of the day, this interface can still be provided.

Unfortunately, I have to go. Once, I'm back I will have a more detailled look into the code, and then hopefully I am able to contribute more useful information about this topic.

Best wishes
Johannes

**Comment by LeErnst** [comment]
Hey @joha2,

thank you for taking time for this request. We are 4 students and we are currently working with pyrate (which is actually quite nice, that this is for free and open source) in a project. 

Yes, you got the important points. The aim is that the optimization method has to handle the boundary conditions and to be able to use a unconstraint optimization method, it is common way to consider the penalty lagrange function. So the unconstraint method will find then a minimum in the feasable set. 

Actually we have already looked (for more than one day :D) at all of the code in `/core` and other subfolders (which is complicated stuff as well), but we did not figure out where the order is set. In `iterators.py` there is the `variables_list`
```
    def collectElement(self, variable, keystring, *args, **kwargs):
          self.variables_list.append(variable)
```
 and we think that with this list we could somehow determine the order, but we dont get it how.

Yes that is okay, if we figure it out before you get back, i write the solution in here.

Best wishes
Lewin

**Comment by joha2** [comment]
Dear @LeErnst,

Yeah, the code is not very easy, since it should be a very general framework. But as far as I understood, the variables are still real. Therefore, you can still rely on the interval functionality of `FloatOptimizableVariable`. The key point is https://github.com/mess42/pyrate/blob/bcdee61aa0c1d13261998a4f6ae7d26a734c728c/pyrateoptics/optimize/optimize.py#L78
where `self.collector` is used to generate the numpy array and feeds it into the dumb backend. Summary for an idea of a first step of modifications:
* Derive a class from `OptimizableVariableActiveCollector` which substitutes `self.collector` in `Optimizer` and returns for every variable instead of single numpy array an array of triples containing the variable value, the left interval boundary, the right interval boundary, or for fewer constraints either inf or None, depending on which is better suited for processing.
* Rewrite `Optimizer` to accept the new collector interface (i.e. array of triples instead of value array).  This means modify `MeritFunctionWrapper` to include your penality function based on the array of triples.
* Provide your backend which accepts modified `x` (triples with interval boundaries instead of just numbers), `x0` and so on.
Maybe the last two points could be integrated into your own `Optimizer` class. With this approach you do not need to know the order anymore, because the intervals are provided for free. Another approach is still to use the `variables_list` and perform the optimization part on your own (you can set values and get values from the list and the optical system is still updated accordingly). Note, that the order of `variables_list` may be changed, if something is changed in the system (i.e. surface type or something like this).

In a second step, we could think about how to integrate these things into the `Optimizer` class, and how to provide a more general interface, allowing such penalty approaches more easily.
We are not optimization experts at all, therefore we need external input. Since we couldn't foresee all needs for implementing a better optimizer, we need to know whether the best interface in this case is. So any ideas are appreciated! :-)

Another two questions: Would you like to tell me the background of your project? Which subject are you studying?

Hope this helps on a first sight. :-)

Best regards
Johannes

**Comment by LeErnst** [comment]
Hello @joha2 ,
this is the key idea:

> returns for every variable instead of single numpy array an array of triples containing the variable value, the left interval boundary, the right interval boundary, or for fewer constraints either inf or None, depending on which is better suited for processing.

We do not need to know which variable is assigned to which opticalsystem-parameter, we only need to know the value and the associated interval. That's a nice solution, thanks for the idea. Our own `ProjectScipyBackend`-class now contains a method `update_PSB` which gets the `Optimizer`-object and it defines the callable function h(x), with the help of the `collector`  as well as it assigns this function to our `ProjectScipyBackend.`  We can then call the `minimize` from scipy within our Backend and pass a lambda expression which sets up the penalty-lagrange function on the fly. The only disadvantage of this approach is that we have to define the `ProjectScipyBackend` first, then the `Optimizer` object and after these steps we can call the `update_PSB` method. So it depends on the order in which the objects are created, but ok it works for our purposes. 

Regarding your last questions: We are all computational science and engineering students and the objective of our project is to find and test new optimization methods in Optic Design

Thank you for the help
Lewin

**Comment by joha2** [comment]
@LeErnst glad to hear that my suggestion worked :-) Please don't hesitate to ask, if there are further questions. As I said, we are always interested in suggestions for improvement. And last but not least: If you will write a paper about your findings, I would be glad to read it, so feel free to post me a link.

Best regards
Johannes
