### ISSUE TITLE
Effective Focal Length Calculation does not work

### ISSUE THREAD

**Issue by fesahin** [mess42/pyrate#138]
It looks like getEffectiveFocalLength and getABCDMatrix under optical_system is broken.

**Comment by joha2** [comment]
Hi @fesahin thanks for reporting. These functions are not operational anymore and should be removed, since they are only usable for rotationally symmetric systems without any freeform components. (Unfortunately, we did not do it, yet :-)) For calculating the linear approximation ray matrices, the class `Aimy` (`raytracer/aim.py`) is used. Maybe there, one could provide a function to calculate the effective focal length. Notice, that `Aimy` is far from having a stabilized API. Further, there are still conceptual problems (i.e. how to perform aiming in an anamorphotic system etc.). Every help is appreciated :-). Independently, I will remove these functions, soon.

Best regards
Johannes

**Comment by joha2** [comment]
The functions are removed, therefore closing this issue.
