### ISSUE TITLE
report: performance of seqtrace

### ISSUE THREAD

**Issue by LeErnst** [mess42/pyrate#140]
Hello, its me again :smile:
i only want to report a weird behaviour of the `seqtrace` function. If you predetermine all bundles and then call the `optical system seqtrace` like
```
            ...
            for j in range(0, len(initialbundle)):
                 my_initialbundle = initialbundle[j]
                 rpaths = my_s.seqtrace(my_initialbundle, sysseq)
                 ...
```
the seqtrace changes the size of my_initialbundle.x/k/Efield at every iteration. I do not know why, but when you optimize some optical system with an algorithm which evaluates gradient or worser the hesse then the raytracer will become very slow after a while. I have fixed it in our code with `copy.copy(initialbundle[j])`.

best regards
Lewin

**Comment by joha2** [comment]
Hey Lewin,

Thanks for reporting this issue and nice to see you again :-) . Could you please provide a minimal working example, such that we can investigate in this?

Thank you!

Best regards
Johannes

**Comment by LeErnst** [comment]
Hey Johannes,

change the meritfunctionrms in `demo_optimize.py` as follows:

```
270 my_initialbundle = RayBundle(x0=o, k0=k, Efield0=E0, wave=wavelength)            
271                                                                                  
272 def meritfunctionrms(my_s):                                                      
273     """                                                                          
274     Merit function for tracing a raybundle through system and calculate          
275     rms spot radius without centroid subtraction. Punish low number of           
276     rays, too.                                                                   
277     """                                                                          
278 #    my_initialbundle = RayBundle(x0=o, k0=k, Efield0=E0, wave=wavelength)       
279     rpaths = my_s.seqtrace(my_initialbundle, sysseq)                             
280     print(len(my_initialbundle.x))                                               
281     print(my_initialbundle.x)                                                    
282                                                                                  
283                                                                                  
284     x = rpaths[0].raybundles[-1].x[-1, 0, :]                                     
285     y = rpaths[0].raybundles[-1].x[-1, 1, :]                                     
286                                                                                  
287     xmean = np.mean(x)                                                           
288     ymean = np.mean(y)                                                           
289                                                                                  
290     res = np.sum((x - xmean)**2 + (y - ymean)**2) + 10.*math.exp(-len(x))        
291                                                                                  
292     return res  
```

**Comment by LeErnst** [comment]
We have further questions regarding the meritfunction. 
-In the definition of the `meritfunctionrms` above we calculate the mean value of all x coordinates and y coordinates to optimize the spot size. In optical design this is one way to get a reference value, but there are others. We want to compute the main ray or chief ray (in german Hauptstrahl: it is the ray which is going right through the middle of the aperture) in order to optimize not only the spot size, but the distortion. Is there an easy way to include this in the `meritfunctionrms`?

-Another issue we are facing is that we want to prevent negative thicknesses of the lenses. To do so we have to calculate all points where the rays pierce the surfaces of the lenses and penalize the `merifunctionrms` value if the distance between two punctures of consecutive surfaces of one ray is negative. Are these puncture points on the surfaces accessible? And if so where?

Thanks and best regards
Lewin

**Comment by joha2** [comment]
Hey Lewin,

Thanks for your fast response! I will try the demo example to check where this comes from and whether it is a feature or a bug :D I'll try to answer your other questions first:

* the chiefray should be the first ray in every raybundle. So 
```Python
x_chief = [r.x[-1, 0, 0] for r in rpaths[0].raybundles]
y_chief = [r.x[-1, 1, 0] for r in rpaths[0].raybundles]
z_chief = [r.x[-1, 2, 0] for r in rpaths[0].raybundles]
``` 
But it may be, that this is not true for all sampling schemes of the raybundles

* Also the puncture points of the surfaces are accessible via the raybundles 
```Python
x_surf_i = rpaths[0].raybundles[i].x[-1, 0, :]
y_surf_i = rpaths[0].raybundles[i].x[-1, 1, :]
z_surf_i = rpaths[0].raybundles[i].x[-1, 2, :]
```
, since pyrate is a sequential raytracer.

Hope this helps on a first sight. I will check the indexing more thoroughly, soon.

Best regards
Johannes

**Comment by joha2** [comment]
@LeErnst I fixed the error by performing a deep copy in seqtrace, such that initialbundle is not modified within the function. Hope this helps.

Best regards
Johannes

**Comment by LeErnst** [comment]
@joha2 thanks for the replies, this will help us a lot.

best regards 
Lewin

**Comment by LeErnst** [comment]
Hey @joha2,

we are done with our project and because you helped us a lot and maybe you guys want to improve the connection between optimization and pyrate we prupose here our project files
https://github.com/LeErnst/ProjectCSE.git
The most interesting file for you is `project_optimize_backends.py` and there is also a project report in german.

best regards
Lewin

**Comment by joha2** [comment]
Hey @LeErnst nice to hear back from you! I'm really glad that our discussions helped you with your project. I also did a first short check of your Projektbericht, which is very nice! When is the project report due? Is there some time left, that I could put some small comments into your document? Would that be of any benefit for you?

As I said: Good work! 

Kind regards
Johannes

**Comment by LeErnst** [comment]
We have had our presentation today and the project report has already been submitted, so it wouldn't help us but thanks for the offer.

**Comment by joha2** [comment]
Nice one! :smiley_cat: How was it going? May I put a link to your project repo into our README.md file?

**Comment by joha2** [comment]
@LeErnst after you worked a long time with pyrate, is it possible to give a short summary on usability, missing features, and things like that? E.g. which is the feature you're missing most?

**Comment by LeErnst** [comment]
It was good, we had a nice discussion about the methods and the found optical systems. Yes you can put the link there and i will briefly sum up the important poinst:
- it would be nice if the lens, coordinate and bundle specifications can be given in a text file which is then automatically been read
-we have used the scipy `minimize` function for self defined optimization function and for this you often need the boundaries of the optimization parameters in a `scipy.optimize.Bounds` object and the gradient of the meritfunction as a callable, this would be nice within your `Optimizer ` object.
But over all the `Optimizer` is quite nice because it is so general.

**Comment by joha2** [comment]
@LeErnst thanks for the review! I'm glad that your presentation went well! I've got a couple of questions, still.

* Text file for lens specification and bundles: How should the format of both be defined? You already implemented a reader: Could you please provide some code for it, such that we do not start at the beginning? Although the convenience functions in `pyrateoptics.__init__.py` were meant as an easy to use interface to a file or to the Python console. Were they not sufficient?
* Optimizer Bounds: Using scipy `Bounds` is maybe a backend problem. We wanted to separate optimization frontend from backend, since people should also be able to use their own optimizer code, if they have no access to scipy (install restrictions or limited Python environment). So the usage of `Bounds` can be put into a `ScipyWithBoundsOptimizerBackend` class. I have to think about this, maybe I come back to you with further questions.
* Optimizer Gradient: This is definitetly a thing for the frontend. I think about a further MeritFunctionGradientWrapper where the user has to take care about calculating the gradient (either analytically or with point formulas) and has to take care that the Wrapper returns a numpy array of correct size. But I how this could be automatically implemented. I will also have to think about it. Do you have any ideas about it?
* You implemented your own optimizer class. I forgot what the reason was: Could you please summarize this in short for me?
* When/If the gradient is implemented, is it useful to have also a Hessian implemented?
* What are useful defaults for the gradient (except None :smile_cat:)?

Best wishes
Johannes
