### ISSUE TITLE
[Question] How does this project compare with pyOpTools?

### ISSUE THREAD

**Issue by iromero91** [mess42/pyrate#142]
I have noticed there are two active python raytracer projects around github. this one and [pyOpTools](https://github.com/cihologramas/pyoptools) I am wondering how much work is being duplicated or if the focus of both projects is indeed completely different?

**Comment by joha2** [comment]
Hi @iromero91 thanks for pointing this out. When we started with Pyrate, we were not aware about other projects and we wanted to start a very general raytracing project which is able to handle very asymmetric systems with all kinds of materials. This is still our goal and it's a spare time project, therefore I assume that it will not reach a production stage soon. 

Because of the general aspect, there are some conceptual problems, which are difficult to solve in spare time project. E.g. Pyrate is at the moment not able to perform a thorough wavefront analysis, although on the other hand it has a quite general optimizer and can handle very complex systems.

I don't think the focus is very different. At the end of the day, all of these projects want to perform raytracing and optimize optical systems to achieve a certain performance specification. 

But for Pyrate, we are curious how far we can go also for specialized materials (anisotropic, grin) or highly asymmetric freeform systems with the usual notions of a standard optical raytracer (aiming, optimization of certain variables, ...).

Maybe at the end of the day this prevents others - who want to have a production ready raytracer - from joining us. Further, if the goal of `pyOpTools` is to "just get this raytracer done" then this is also not compatible with our goals, I'm afraid.

Nevertheless, we are open for questions, critics, and of course contributions :-)

Best wishes
Johannes
