### ISSUE TITLE
OPD calculation at reference surface

### ISSUE THREAD

**Issue by nvladimus** [mess42/pyrate#146]
Hi, everyone,
First off - great project! I would love to use it and hopefully contribute.
Can Pyrate calculate OPD (optical path difference) or relative phase of rays when they hit a reference surface (sphere)?

**Comment by joha2** [comment]
Hey @nvladimus thanks for your nice offer :smile: 

At the moment rays (Raybundle) only have access to the geometrical points where they hit a surface. This means from that you can only calculate a geometrical path length. We did not have a good idea, yet, on how to give rays access to the material such that it can calculate an OPD. The problem here is that rays and materials are different object categories. One is the light propagating through the system and one is a system inherent property. (A ray has also an electrical field and a k vector. But I don't know whether this helps for calculating the OPD.)

Best wishes
Johannes

**Comment by nvladimus** [comment]
Thanks!

**Comment by joha2** [comment]
@nvladimus I added a phase analysis to my fork of pyrate (in `pyrateoptics/raytracer/analysis/ray_analysis.py`). It uses the x values of the RayBundles and their respective k values to get the phases of the plane wave decomposition. I checked that they are almost identical for several rays for focusing optical systems, so maybe you could also use this as an OPD. But you have to be very careful and should check the code before using it. You may use them in the following manner:
`RayPathAnalysis(ray).get_relative_phase_difference(raypath, [referenceray=None, wavelength=None])`. If `referenceray` is provided, its phase value is subtracted from the rest. If `wavelength` is provided (in mm) the phase value is divided by it giving the error in waves instead of mm.

These analysis are preliminary and will maybe change in the future.

Best regards
Johannes

**Comment by nvladimus** [comment]
Many thanks, Johannes!

**Comment by ivoihrke** [comment]
Hi, I would also be interested in this feature. Isn't it that the k-vector is scaled according to the local index ? This would give access to the scale factor that needs to be applied to the respective rays segment to turn geometric path length into optical path length.

**Comment by joha2** [comment]
@ivoihrke I added this only to my fork because I am not sure whether it is correct. I think in a first approximation it would give the right results, but I am not sure about the validity of this approximative approach. Further for the k vector, we divided it by 2pi/lambda such that it is of size unity (just like epsilon) and therefore it is a measure of the local index, as you said. Due to the solution of the general dispersion relation for anisotropic media it also gives the expected results for the different rays in those media. So, I would be glad if somebody could check the assumptions of this code and verify its correctness.

(I think at least a point where this approach breaks down is where the plain wave approximation for rays is invalid, e.g. near focal points.)
