### ISSUE TITLE
Learing pyrate

### ISSUE THREAD

**Issue by RWL-69** [mess42/pyrate#148]
Hello,

My field is electronics but I have done some optics work as well and looking for a Linux based program.  I have searched for instructions and tutorials on using pyrate and pyrate in FreeCAD with no luck.  I have never programmed in python.

Today I was working with pyrate and modifying the demo programs to try to understand the options and how to create lens systems.  As my understanding of optics is limited, but I have used a different ray tracing program in the past, I was expecting certain results from the demos.

I was playing with demo_asphere.py and changing positions of various items to understand what the command settings do.  I ran into two problems that I am not sure if it is the program or my lack of understanding on how the program works.

I was trying to move the image surface closer and farther from the lens and found that the ray trace was still turning into a spot.  It didn't matter what value I entered in for decz.  To me this is wrong as the source is supposed to be parallel.  

Second, if I changed the position either to close or two far away, the program created an image that didn't make any sense.  Now I think this is related to calculations going outside some limits as the curve image (lens) was corrupted as well.  This also seemed to occur if I changed the radius of the source.

Without knowing how to use the program properly it is hard to say if it is a program bug or a error on my part.

I was hoping that there would be links for tutorials on the wiki or via FreeCAD but I didn't find anything.  And if I searched for pyrate and FreeCAD, I don't find anything of use. 

Robin

**Comment by joha2** [comment]
Hey @RWL-69 

Thanks for using pyrate! We appreciate every hint or question about it. 

First of all: The FreeCAD interface is just some kind of mock up which is broken after our last refactor from 2017. I'm sorry, the information about that is quite distributed over the README.md and the wiki. So we had some ideas of how to implement the FreeCAD interface, but the coupling between the classes of FreeCAD and pyrate is quite tight. This means, that if something changes in pyrate (whose API is not settled, yet) then you basically have to reimplement the FreeCAD interface. 

Either way: To use the mockup you have to copy the pyrate directory into the Mod directory of FreeCAD (or use the addon manager). Then there should appear a new workbench within the workbench selection combobox. Although, expect many error messages.

The demo issue: The `demo_asphere.py` file is for demontrating the ability to optimize an optical system. Therefore it is no surprise that you cannot see anything, since the optimizer changes the radius and the aspherical coefficients of the surface accordingly after you changed the decz.

I would suggest to start with demo_doublet.py. This is a simple optical element where you can see how to construct the coordinate systems, the surface shapes and the apertures. At the end of the day there are some rays traced through the system and an image is drawn.

For more complicated systems, I would recommend to use the convenience function `build_simple_optical_system` and modify the contents of the optical system from there.

Unfortunately, the usage of the demos as well as pyrate without FreeCAD interface is not that easy without any experience in Python. Do you have experiences in other programming languages?

In case of any problems don't hesitate to ask.

Best wishes
Johannes

**Comment by RWL-69** [comment]
Hello Johannes,

Thank you for the quick response.

I do have some experience in various languages from assembly to C and other scheme languages as required.  I have programmed Arduinos in recent years.  It is far from my field though.  I will learn what I need and that is why I was testing with different demos.

I have no issues working from the Command Line so I don't need FreeCAD at all.  I just have the optics designed in it for mechanical integration into our system so FreeCAD would be the bonus but not necessary at this time.  I used that addon manager for installing pyrate into FreeCAD.  

 I will stick with the command line for now.

For previous raytracing I have been "Optical Ray Tracer".  [https://arachnoid.com/OpticalRayTracer/](url) and was trying to compare results.

I could run the demos and I was learning some of the aspects but without documentation it is a trial and error process.  I actually started with the demo_anisotropic_mirror.py as that was just flat surfaces.  

Is there a set of documents for the various parts of the descriptions for pyrate?  If there is, then it should be linked off of the wiki.  If the demos were better commented it would also help as a learning tool.  But that is one of the issues that I am even bad with, commenting my code.  :)

When I am looking at the demos I am trying to find out what the procedure for defining the lens array in the system is like so I started by changing different variables in lines like this.

` lc2 = s.addLocalCoordinateSystem(
        LocalCoordinates(name="surf2", decz=5.0, tiltx=10*math.pi/180.0),
        refname=lc1.name) `

 Is build_simple_optical_system part of FreeCAD or the python code?   I cannot find it.  I can find build_demo_optimize_goptical though.

Tried demo_doublet.py and it did what I was expecting.  Thank you for the suggestion.

Robin

**Comment by joha2** [comment]
Hey Robin,

Thanks for your fast response. OK, so you have quite lots of experience. Our code is highly object oriented. The main classes are `LocalCoordinates`, `OpticalSystem`, `OpticalElement`, `Surface`, `Shape` (and subclasses) as well as BaseAperture and subclasses. Usually the optical system is defined, by setting up some interconnected `LocalCoordinates` assigning them to `Surface`s with a certain shape and aperture. You're right, the demos could be better documented, that's definitely on our TODO list. But as I said, the API is not settled, yet. Therefore I'm afraid you have to dig through the code. Although, the demos should provide an idea, on how to setup different parts. Unfortunately, for the API there is no real document :-(

But the way of defining an optical system is always the same:

* create an empty system via `system = OpticalSystem.p(name="opticalsystem")`
* create an interelated set of `LocalCoordinates` via `lcX = LocalCoordinates.p(name="bla", decx=0., decy=0., decz=0., tiltx=..., tilty=..., tiltz=..., refname=other_localcoordinates.name)` where `decx, decy, decz, tiltx, tilty, tiltz` are always in relation to other_localcoordinates
* create surfaces by using `surfX = Surface.p(localcoordinates, shape=..., aperture=...)`
* where `shape` is from `raytracer.surface_shapes` and `aperture` is from `raytracer.apertures`
* create materials from `raytracer.materials....`
* create opticalelements by using `OpticalElement.p(localcoordinates, name="opticalelement")`
* add materials and surfaces to optical element
* add element to optical system `system.addElement`
* define sequence of surfaces for sequential raytracing `seq = [("elem1name", [("surf1name", optionsdict1), ("surf2name", optionsdict2), ... ("surfnname", optionsdictn)]), ("elem2name", [ ... ])]`

Then raytrace via `raytrace` and draw via `draw`.
`raytrace` and `draw` are defined where the `build...` functions are defined, namely in `pyrateoptics.__init__.py`. The `build...` functions are the short way of doing the whole list of administrative stuff above. Check the example code in the README.md as well as the wiki main page.

The idea is that the core components of pyrate are stand alone and FreeCAD is mainly for point & click experience and representation of the system.

Hope this helps on a first sight.

Best wishes
Johannes

**Comment by RWL-69** [comment]
Hello Johannes,

It is a start.  

These pointers that you sent should be on the wiki.

Now to start learning more about it.

Robin

**Comment by joha2** [comment]
> These pointers that you sent should be on the wiki.

Hey @RWL-69 you're right. These things really should be on the wiki. I will put the points there after a bit of polishing.

Best wishes
Johannes

**Comment by joha2** [comment]
@RWL-69 I added the points above to the wiki. First: could you please have a look whether they are clear enough written? Second: do you think the wiki is the best location or should they be added to the README.md?

Best wishes
Johannes

**Comment by RWL-69** [comment]
Hello Johannes.

That looks like a great starting point.  Much easier than trying to learn blindly from the demos.  I will look at it more in the next couple of days.

Be safe.  Robin
