### ISSUE TITLE
Full sphere

### ISSUE THREAD

**Issue by ianbell87** [mess42/pyrate#149]
Hello.

First of all, thank you very much for the work on this library. Its already proved quite useful. As I am learning the library (and about optics in general) I was trying to simulate a ball lens (sphere of solid glass). What I noticed, is that if I set the front and rear surface curvatures to be the exact same magnitude there are a number of RunTime warnings. Full code here:

```python
s = OpticalSystem.p()


lc1 = s.addLocalCoordinateSystem(LocalCoordinates.p(name="surf1", decz=0.0), refname=s.rootcoordinatesystem.name)
lc2 = s.addLocalCoordinateSystem(LocalCoordinates.p(name="surf2", decz=32.0), refname=lc1.name)
lc3 = s.addLocalCoordinateSystem(LocalCoordinates.p(name="image", decz=10), refname=lc2.name)

frontsurf = Surface.p(lc1, shape=Conic.p(lc1, curv=1./16.0), aperture=CircularAperture.p(lc1, maxradius=14))
rearsurf = Surface.p(lc2, shape=Conic.p(lc2, curv=-1./16.0), aperture=CircularAperture.p(lc2, maxradius=14))
image = Surface.p(lc3)

elem = OpticalElement.p(lc1, name="ball_lens")

bk7 = ConstantIndexGlass.p(lc1, n=1.5168)

elem.addMaterial("BK7", bk7)

elem.addSurface("front", frontsurf, (None, "BK7"))
elem.addSurface("rear", rearsurf, ("BK7", None))
elem.addSurface("image", image, (None, None))

s.addElement("ball_lens", elem)

sysseq = [("ball_lens",
           [
            ("front", {}),
            ("rear", {}),
            ("image", {})])]

r1 = raytrace(s, sysseq, 20,
              {"startz": -25, "radius": 10, "raster": raster.MeridionalFan()},
              wave=wavelength)[0]
r2 = raytrace(s, sysseq, 20,
              {"startz": -13, "starty": 24, "anglex": math.radians(-45), "radius": 14, "raster": raster.MeridionalFan()},
              wave=wavelength)[0]
r3 = raytrace(s, sysseq, 20,
              {"startz": -22, "starty": 16, "anglex": math.radians(-22.5), "radius": 11, "raster": raster.MeridionalFan()},
              wave=wavelength)[0]
draw(s, [(r1, "blue"), (r2, "red"),  (r3, "green")])
```

Warnings:

`
c:\rd\repositories\pyrate\pyrateoptics\raytracer\surface_shape.py:312: RuntimeWarning: invalid value encountered in true_divide
  t = G/division_part
c:\rd\repositories\pyrate\pyrateoptics\raytracer\aperture.py:113: RuntimeWarning: invalid value encountered in greater_equal
  (x**2 + y**2 >= self.annotations["minradius"]**2) *
c:\rd\repositories\pyrate\pyrateoptics\raytracer\aperture.py:114: RuntimeWarning: invalid value encountered in less_equal
  (x**2 + y**2 <= self.annotations["maxradius"]**2))
c:\rd\repositories\pyrate\pyrateoptics\raytracer\material\material_isotropic.py:110: RuntimeWarning: invalid value encountered in greater
  valid = (square > 0)
`

The output image is missing a large number of rays. If modify the curvature of the rear surface by a small amount (ie 1/16.1) the system resolves just fine. I'm wondering if this is a bug or simply a limitation of the underlying system?

Since I'm asking questions, one other thing that I was trying to understand is why all the supporting objects (shapes, apertures, materials) require a co-ordinate system in their construction? I really liked the demo_asphere.py example which showed how to use the shortcut notation to build a simple lens system. However, when I tried to use this notation to build a system with defined apertures for each surface I run into the issue that the aperture object requires a co-ordinate system. Since the co-ordinate system is created within the shortcut function its not possible for me to pass it in. Maybe I'm missing something, but it seems odd that materials and such need the co-ordinate system object.

Thanks again for the great work!

**Comment by joha2** [comment]
Hey @ianbell87 

Thanks for using pyrate and thanks for your nice questions!

Indeed the first one is a "bug" in the solution of the `Conic` surface. You can observe a similar behavior in the `demo_rainbow.py` file where the droplet is supposed to be spherical.

The problem here is, that the analytical solution consists of two roots. The ray intersection point lies exactly on the surface (which represents one root) which means when a ray starts there and is supposed to hit another spherical surface the algorithm thinks the smaller root (i.e. zero) is the correct solution (this also depends a little on numerical errors, therefore in your example some rays are ok, some not). I am not really sure whether this could be solved in a reasonable fast manner. Until now we had no good idea. As a workaround we just used the Asphere surface to use a numerical algorithm instead of an analytical solution. Maybe another intermediate plano surface helps, but I'm not sure. I will try that.

Your other question is also quite interesting: Our goal was to make the system definition as general as possible. Therefore, every quantity gets its own local coordinate system. For isotropic materials, you're right, there it is of no use. For anisotropic or GRIN materials the local coordinate system indeed matters.
You're also right that the explicit usage of coordinate system for the aperture or shape object is quite tedious, in particular if you want to use the same as the surface. But we had no good idea how to inherit the local coordinate system from the super object (i.e. an aperture which inherits its local coordinate system from its corresponding surface object).

So if you have a nice idea about it, we are all ears :smile_cat: 

Anyway, the coordinates are available. When you defined a surface `surf1`, you can use its local coordinate system by calling `surf1.rootcoordinatesystem`. But this is useless if you want to initialize the aperture and shape within the `surf1 = Surface.p(...)` call since you cannot access `surf1.rootcoordinatesystem`.

Hope this helps for now.

Best wishes
Johannes

**Comment by joha2** [comment]
A middle surface helps, since it avoids finding a solution which is already found due to the double root.

![sphere_with_middle_surf](https://user-images.githubusercontent.com/12564815/79615384-ec253300-8102-11ea-9011-24a9f5013b4e.png)

See your code which I slightly modified in the following:

```Python
from pyrateoptics.raytracer.optical_system import OpticalSystem
from pyrateoptics.raytracer.optical_element import OpticalElement
from pyrateoptics.raytracer.localcoordinates import LocalCoordinates
from pyrateoptics.raytracer.surface import Surface
from pyrateoptics.raytracer.material.material_isotropic import ConstantIndexGlass
from pyrateoptics.raytracer.surface_shape import Conic
from pyrateoptics.raytracer.aperture import CircularAperture
from pyrateoptics.sampling2d import raster
from pyrateoptics import raytrace, draw

import math

s = OpticalSystem.p()

wavelength = 0.550e-3

lc1 = s.addLocalCoordinateSystem(LocalCoordinates.p(name="surf1", decz=0.0), refname=s.rootcoordinatesystem.name)
lc15 = s.addLocalCoordinateSystem(LocalCoordinates.p(name="middle", decz=16.0), refname=lc1.name)
lc2 = s.addLocalCoordinateSystem(LocalCoordinates.p(name="surf2", decz=16.0), refname=lc15.name)
lc3 = s.addLocalCoordinateSystem(LocalCoordinates.p(name="image", decz=10), refname=lc2.name)

frontsurf = Surface.p(lc1, shape=Conic.p(lc1, curv=1./16.0), aperture=CircularAperture.p(lc1, maxradius=14))
middlesurf = Surface.p(lc15, shape=Conic.p(lc15), aperture=CircularAperture.p(lc15, maxradius=16))
rearsurf = Surface.p(lc2, shape=Conic.p(lc2, curv=-1./16.0), aperture=CircularAperture.p(lc2, maxradius=14))
image = Surface.p(lc3)

elem = OpticalElement.p(lc1, name="ball_lens")

bk7 = ConstantIndexGlass.p(lc1, n=1.5168)

elem.addMaterial("BK7", bk7)

elem.addSurface("front", frontsurf, (None, "BK7"))
elem.addSurface("middle", middlesurf, ("BK7", "BK7"))
elem.addSurface("rear", rearsurf, ("BK7", None))
elem.addSurface("image", image, (None, None))

s.addElement("ball_lens", elem)

sysseq = [("ball_lens",
           [
            ("front", {}),
            ("middle", {}),
            ("rear", {}),
            ("image", {})])]

r1 = raytrace(s, sysseq, 20,
              {"startz": -25, "radius": 10, "raster": raster.MeridionalFan()},
              wave=wavelength)[0]
r2 = raytrace(s, sysseq, 20,
              {"startz": -13, "starty": 24, "anglex": math.radians(-45), "radius": 14, "raster": raster.MeridionalFan()},
              wave=wavelength)[0]
r3 = raytrace(s, sysseq, 20,
              {"startz": -22, "starty": 16, "anglex": math.radians(-22.5), "radius": 11, "raster": raster.MeridionalFan()},
              wave=wavelength)[0]
draw(s, [(r1, "blue"), (r2, "red"),  (r3, "green")])
```

All in all you have three possibilities:

* deforming the second surface slightly (introducing conic, radius deviation) -> considered non-optimal solution
* using a numerical formula by using `Asphere`
* using an intermediate surface

At the end of the day, it is maybe most useful to put three surfaces together into an optical element named `Sphere` and afterwards use that for every spherical lense appearing within the design.

Best wishes
Johannes

**Comment by ianbell87** [comment]
Hi Johannes,

Thanks for the great input. As you mentioned, adding the intermediate surface is a pretty simple solution with no real downsides.

Regarding the co-ordinate system attached to each object. As I am quite new to optics and especially simulators such as pyrate, it didn't occur to me that there would be circumstances where the material was dependent on a co-ordinate system. After looking at anisotropic and GRIN materials a little bit I can see why this becomes important. I'm definitely too new to this domain and library to offer any better solutions!

Cheers
Ian
