### ISSUE TITLE
Can't understand the difference between `seqtrace` and `para_seqtrace`

### ISSUE THREAD

**Issue by kouui** [mess42/pyrate#166]
Thank you for this very instructive raytracing library.

In `demos/demo_mirrors.py`, I compared the raytracing result generated by
```python
r1r = s.seqtrace(initbundle1, sysseq)
```
and 
```python
(pp1, r1p) = s.para_seqtrace(a.pilotbundle, initbundle1, sysseq)
```

as shown in the following figures, it turns out that `para_seqtrace` is able to have a focus point after M1 mirror while `seqtrace` failed in focusing the rays. This is wierd to me, in my opinion a simple Fresnel's law will be able to focus that raybundles since it is a isotropic conic. Did I make something wrong? What is the difference between this two methods? 

Figure. para_seqtrace
![para_seqtrace](https://user-images.githubusercontent.com/22701382/96860489-c572fb00-149d-11eb-8260-c071ee7b890b.png)

Figure.seqtrace
![seqtrace](https://user-images.githubusercontent.com/22701382/96860523-ce63cc80-149d-11eb-8347-2ba77ebcaea3.png)

**Comment by joha2** [comment]
Dear @kouui 

Thanks for using pyrate! You did nothing wrong, your code works as intended:

* `seqtrace` performs a full geometric raytrace which means, there are no approximations applied
* `para_seqtrace` performs a paraxial seqtrace based on the pilotray (as a generalization of an optical axis) and the first order properties of the reflection/refraction (by using an approximative matrix formalism)

While the former contains all types of aberrations, the latter is free of aberrations. Therefore, the `para_seqtrace` provides an ideal focus point between mirror 1 and 2 while `seqtrace` leads to aberrations which can be seen by the "chiefray" missing the intersection of the two marginal rays.

Hope this helps!

Best wishes
Johannes

**Comment by kouui** [comment]
Dear @joha2 
Thanks for your quick reply!!

Sorry for not being farmiliar with optics. 
The conic constant is 0 so the shape is circle. With this shape the collimated incident rays will not have an ideal focus point, therefore we see aberrations. Am I correct?

**Comment by joha2** [comment]
Hey @kouui no problem!

Yes, a collimated bundle reflected at a sphere always result in aberrations (see #157 last entry). In contrast you will get an ideal focus for a paraboloid (cc = -1). In the system above, an additional difficulty is that the rays hit the surface at an off-axis position, so you will also get some asymmetric aberrations (like coma if I remember correctly). Correct, for a real ray trace, you have to use `seqtrace`.

Best wishes
Johannes

**Comment by kouui** [comment]
Dear @joha2  Okay! I see! Thank you so much.

Sorry for asking you question again.

In source code `pyrateoptics/raytracer/optical_element.py`, there is a variable `refract_flag` that if the surface is a mirror (reflection), then `current_material` is set to the current background material
```python
    def seqtrace(self, raybundle, sequence, background_medium, splitup=False):

        current_material = background_medium
        [...]
            if refract_flag:
                current_material = self.findoutWhichMaterial(mnmat,
                                                             pnmat,
                                                             current_material)
            else:
                pass

            current_material_deflection = {True: current_material.refract,  False: current_material.reflect}

            for rp in rpaths:
                current_bundle = rp.raybundles[-1]
                raybundles = current_material_deflection[refract_flag](
                                                     current_bundle,
                                                     current_surface,
                                                     splitup=splitup)
        [...]
```
after which, `current_material.reflect(...)` is called to generate the relfected raybundles.

However, it seems that, as the following function definition in `pyrateoptics/raytracer/material/material_isotropic.py`, `xi` is calculated by `self.calc_xi_isotropic(xlocal, normal, k_inplane, wave=raybundle.wave)` where `self` is current background material, and no information about the material of the mirror (for example Ag,) is passed into `self.calc_xi_isotropic(...)` and `self.calc_e_field(...)`. While, actually the reflected E field does depend on the refractive index on both side of the mirror. 
```python
    def reflect(self, raybundle, actualSurface, splitup=False):
        """
        Reflection in isotropic material.
        """

        k1 = self.lc.returnGlobalToLocalDirections(raybundle.k[-1])
        normal = raybundle.getLocalSurfaceNormal(actualSurface, self,
                                                 raybundle.x[-1])
        xlocal = self.lc.returnGlobalToLocalPoints(raybundle.x[-1])

        valid_normals = checkfinite(normal)
        # normals or sag values could either be nan or infinite
        # TODO: remove those normals from calculation

        k_inplane = k1 - np.sum(k1 * normal, axis=0) * normal

        (xi, valid_refraction) = self.calc_xi_isotropic(xlocal,
                                                        normal,
                                                        k_inplane,
                                                        wave=raybundle.wave)

        valid = raybundle.valid[-1] * valid_refraction * valid_normals

        k2 = -k_inplane + xi * normal

        orig = raybundle.x[-1][:, valid]
        newk = self.lc.returnLocalToGlobalDirections(k2[:, valid])

        Efield = self.calc_e_field(xlocal, normal, newk, wave=raybundle.wave)
```

How do you connect `n2` (e.g. the refractive index of the mirror) to the reflected E field?

Thanks for your attention to this matter!!
kouui

**Comment by joha2** [comment]
Dear @kouui 

Thank you for your though question :smile: 

`seqtrace` traces the rays in a sequential manner. Therefore it has to find out which material is behind the current surface and which is after the current surface. The background material is only used if either of these is `None`. For a mirror the material is not considered in the sense that the k-vectors are only reflected, but the material dispersion relation is solved exactly, therefore for the raytracing it is only relevant that the mirror reflects the light, but the material before the mirror may be arbitrary (in particular also anisotropic, see `demo_mirror_anisotropic.py`).

Which brings me to the second point: The E-field. Here a big word of warning: Do not rely on the calculation of the E-field! For anisotropic media it is calculated correctly in principle (as eigenvectors of the dispersion relation), but neither the boundary conditions (Fresnel equations) nor the correct calculation in an isotropic medium are considered. So any polarization related calculation is most probably wrong in pyrate. In particular the function `calc_e_field` in `material_isotropic.py` is wrong, since the E-field is calculated as cross product between k and ey, which gives the correct result for the Poynting vector for general k, but leads to wrong results if k ~ ey. So, please be careful. 

The Fresnel equations are definitely on our long term TODO list, but I think this will not be fixed in a short term.

Best wishes
Johannes

**Comment by kouui** [comment]
Dear @joha2 

Okay! I see. Thank you for your detailed explanation.

Best regards,
kouui
