### ISSUE TITLE
Seeking Help: Modeling Lenslet Array

### ISSUE THREAD

**Issue by bakarihassan** [mess42/pyrate#173]
Thanks for all the development to date! I'm trying to design a lightfield camera consisting of a simple lens and a lenslet array (all lenslets having the same z coordinate) spanning the focal plane. However, I'm only able to trace rays through one of the lenslets. Here is what I've attempted so far:

1) I've tried inserting each lenslet in the system sequence, but rays are only traced through the first lenslet in the sequence. If my understanding is correct, this makes sense since it is sequential by definition.

2) I've also tried creating multiple elements, each with the primary lens and one of the lenslets, and the image. These were then combined into the same system...with the same result as above.

3) Finally, I tried creating multiple systems (primary + lenslet + image) and plotting them all in the same plot. However, I could not find a way to have them all show up in the same plot without modifying the draw function.

My next idea would be to combine all the lenslets as if they're one single optic so everything is still sequential, but I haven't been able to figure out how to do that (or any way to present lenslets as multiple optics in parallel). Does pyrate have the native ability to do something like this? I understand it is still under development, so I am willing to "hack" a way if I need to. But some guidance would be greatly appreciated since I am still trying to wrap my head around how it all works.

Background: I have dabbled in basic geometrical optics from coursework, but I do not have experience with optical design software.

**Comment by joha2** [comment]
Hey @bakarihassan!

Thanks for your questions and comments and sorry for the late answer. Yes, the draw function is not able to deal with several system, that is true. I'm not sure whether this is a problem at all. But yes, maybe sometimes one wants to draw several system at once. Anyway, I think the draw function to date is a big mess due to the large input parsing at the beginning. For the lenslet array it seems that you almost tried all functionality pyrate has to offer. One more idea comes to my mind, I don't know whether this works: just implement the other lenslets into the system and modify the sequence (which controls the sequential raytracing) for calculating the rays for every different lenslet, such that they look like
```Python
seq1 = [('elem', [('obj',{}), ('lenslet1',{}), ('im',{})])]
seq2 = [('elem', [('obj',{}), ('lenslet2',{}), ('im',{})])]
# ...
```
With this you can trace several raybundles with different sequences through the system 
```Python
rays1 = raytrace(system, seq1, ...)
rays2 = raytrace(system, seq2, ...)
# ...
```
and draw them at the end by using
```Python
draw(system, rays1, rays2, ...)
```
Please try it out and tell me, whether it helps or not.

Best wishes
Johannes

**Comment by bakarihassan** [comment]
Hi Johannes,

Thanks for the response. I tried your suggestion for two ray bundles, and I am running into the same issue where it only draws the first ray bundle input to the draw function. If I swap the order, it draws the other bundle.

No worries, though. I can write my own code to model the array. I still look forward to using pyrate to learn more about optical design!

Thanks,
Bakari
