### ISSUE TITLE
PyrateInterface.OSinterface.os = pickle.load(input)

### ISSUE THREAD

**Issue by xt9527514048** [mess42/pyrate#23]
Thanks for the authors in advance, your programm provides easy-understanding codes to study and design the optical system.

When using 3D graphical interface freecad, I find that when loading pyrate file optical_sys.pkl
the freecad return errors as follow

File "/home/xtt/.FreeCAD/Mod/pyrate/PyrateWorkbench/LoadSystem.py", line 62, in Activated
PyrateInterface.OSinterface.os = pickle.load(input)

'module' object has no attribute 'OSinterface'

is it a bug , or I miss something?
Im waiting for your reply,thanks!

Teng Xu @ Nanjing
email addr: ustcoptic@163.com

**Comment by joha2** [comment]
Hi xt, 

thank you for your bug report! Actually the FreeCAD interfaces undergoes strong changes at the moment due to structural changes of the core code and not frozen design of interfaces to the core code. The codeline you mentioned above is not settled anyway and will soon be removed. There is at the moment no good idea how to save an optical design in a less but best effort manner. So if you have comments or ideas, they will be very appreciated.

Best wishes
Johannes

**Comment by xt9527514048** [comment]
Hallo，Johannes：
Thanks for your reply!
I'm trying to build a automatic optical system optimizer using a global optimization algorithm to minimize the spot size.  The algorithm is  immature and under test.  I find that when the number of variables increases, even with a global optimizer the merit function will soon converge or  the optimizer gives a unrealistic layout. 
When the optimizer become more robust, maybe it can be integrated into pyrate.  
Alles Gute!
Teng Xu @ Nanjing

**Comment by joha2** [comment]
That's a very nice idea! We would be very glad to have some nice optimizer. At the moment there is just an interface to some general scipy code. Although it works it's maybe not the best option. You can just fork from this repo and play around a bit with the core/optimize.py file. Most of the code in there is management code. The optimization code actually is quite small. But the interface is written in a manner that you can plug your optimizer in very easily. If not then we maybe have to change the interface :-). If you have some questions do not hessitate to ask us.

Best wishes
Johannes
